import { NextRequest, NextResponse } from 'next/server';
import { notFound, redirect } from 'next/navigation';

/**
 * Handle Shopify cart checkout URLs like /cart/c/CART_ID?key=KEY
 * These URLs are generated by Shopify but need to redirect to the actual Shopify checkout
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const searchParams = request.nextUrl.searchParams;
  const key = searchParams.get('key');

  if (!id || !key) {
    return notFound();
  }

  // Extract the cart ID from the Shopify format (remove any URL encoding issues)
  const cartId = id;

  // Build the proper Shopify checkout URL
  // This should redirect to the actual Shopify-hosted checkout
  const shopifyDomain = process.env.SHOPIFY_STORE_DOMAIN;
  if (!shopifyDomain) {
    console.error('SHOPIFY_STORE_DOMAIN not configured');
    return NextResponse.json(
      { error: 'Checkout configuration error' },
      { status: 500 },
    );
  }

  // Convert the cart URL to a proper Shopify checkout URL
  // For some Shopify setups, this might be a different format
  const checkoutUrl = `https://${shopifyDomain}/cart/${cartId}:${key}`;

  // Redirect to the actual Shopify checkout
  redirect(checkoutUrl);
}
