import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavLink from "@/components/NavLink";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen flex flex-col`}
      >
        <header className="w-full border-b bg-white/80 backdrop-blur sticky top-0 z-30 shadow-sm">
          <div className="max-w-5xl mx-auto flex items-center justify-between px-6 py-4">
            <a
              href="/"
              className="text-xl font-bold tracking-tight text-gray-900 hover:text-blue-600 transition"
            >
              Lab Essentials
            </a>
            <nav className="flex gap-6 text-gray-700 text-base">
              <NavLink href="/">Home</NavLink>
              <NavLink href="/cart">Cart</NavLink>
            </nav>
          </div>
        </header>
        <main className="flex-1 w-full max-w-5xl mx-auto px-4 sm:px-6 py-8">
          {children}
        </main>
        <footer className="w-full border-t bg-white/80 backdrop-blur py-4 mt-8">
          <div className="max-w-5xl mx-auto px-6 text-center text-gray-500 text-sm">
            &copy; {new Date().getFullYear()} Lab Essentials. Powered by Shopify
            &amp; Next.js.
          </div>
        </footer>
      </body>
    </html>
  );
}
