import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import AnnouncementBar from "@/components/AnnouncementBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen flex flex-col`}
      >
        <AnnouncementBar />
        <Header />
        <main className="flex-1 w-full mx-auto max-w-7xl px-6 mt-10 md:mt-12">
          {children}
        </main>
        <footer className="w-full border-t bg-white/80 backdrop-blur py-4 mt-8">
          <div className="max-w-7xl mx-auto px-6 text-center text-gray-500 text-sm">
            &copy; {new Date().getFullYear()} Lab Essentials. Powered by Shopify
            &amp; Next.js.
          </div>
        </footer>
      </body>
    </html>
  );
}
