name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Check for unused exports
        run: npx ts-prune

      - name: Build
        run: npm run build

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          CI: true

      - name: Run Lighthouse CI
        run: npm run lh
        env:
          CI: true

      - name: Upload Playwright Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Upload Lighthouse CI Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lhci-report
          path: ./.lighthouseci/
          retention-days: 7
